- name: ollama/qwen2.5-coder:14b
  extra_params:
    num_ctx: 65536

- name: ollama_chat/qwen2.5-coder:14b
  extra_params:
    num_ctx: 65536

- name: ollama/qwen2.5-coder:32b
  extra_params:
    num_ctx: 65536

- name: ollama_chat/qwen2.5-coder:32b
  extra_params:
    num_ctx: 65536
    
- name: ollama/mistral-small:latest
  extra_params:
    num_ctx: 65536

- name: ollama_chat/mistral-small:latest
  extra_params:
    num_ctx: 65536

- name: ollama/deepseek-r1:14b
  extra_params:
    num_ctx: 65536
    
- name: ollama_chat/deepseek-r1:14b
  extra_params:
    num_ctx: 65536

- name: ollama/deepseek-r1:32b
  extra_params:
    num_ctx: 65536

- name: ollama_chat/deepseek-r1:32b
  extra_params:
    num_ctx: 65536
