- name: ollama/qwen2.5-coder:14b
  extra_params:
    num_ctx: 65536

- name: ollama_chat/qwen2.5-coder:14b
  extra_params:
    num_ctx: 65536
    
- name: ollama/mistral-small:latest
  extra_params:
    num_ctx: 65536

- name: ollama_chat/mistral-small:latest
  extra_params:
    num_ctx: 65536

- name: ollama_chat/mistral-small3.1:latest
  extra_params:
    num_ctx: 65536

- name: ollama/deepseek-r1:14b
  extra_params:
    num_ctx: 65536
    
- name: ollama_chat/deepseek-r1:14b
  extra_params:
    num_ctx: 65536

- name: ollama/qwq:latest
  extra_params:
    num_ctx: 65536

- name: ollama_chat/qwq:latest
  extra_params:
    num_ctx: 65536

- name: ollama/openthinker:latest
  extra_params:
    num_ctx: 65536

- name: ollama/deepscaler:latest
  extra_params:
    num_ctx: 65536

- name: ollama_chat/deepcoder:latest
  extra_params:
    num_ctx: 65536

- name: ollama_chat/llama3.2-vision:latest
  extra_params:
    num_ctx: 65536

- name: openrouter/deepseek/deepseek-r1:free

- name: openrouter/deepseek/deepseek-r1-zero:free

- name: openrouter/deepseek/deepseek-chat-v3-0324:free

- name: openrouter/google/gemini-2.0-flash-thinking-exp:free

- name: openrouter/google/gemini-2.5-pro-exp-03-25:free

- name: openrouter/meta-llama/llama-4-scout:free

- name: openrouter/meta-llama/llama-4-maverick:free